<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Features</name>
   <tag></tag>
   <elementGuidId>c9a9786c-6d73-4421-af9c-f71bc4129f85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header_nav_feature-id']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header_nav_feature-id > div.css-lzb7d6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bb1bbf2a-0cdd-44cd-bdfa-4679f87ab313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-lzb7d6</value>
      <webElementGuid>0f80ab39-c02c-4a12-8666-d47e30c80083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Features</value>
      <webElementGuid>8c21d778-9bfb-40fd-9f89-612c0ee85200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_nav_feature-id&quot;)/div[@class=&quot;css-lzb7d6&quot;]</value>
      <webElementGuid>061cf290-6090-46db-8e52-20e6b1ffa1ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header_nav_feature-id']/div</value>
      <webElementGuid>438e2a9b-893e-4512-958e-d7054a04d2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[18]</value>
      <webElementGuid>63cfd306-b876-4057-982e-1dccf7d7d2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of use'])[1]/preceding::div[31]</value>
      <webElementGuid>47c5c7e5-6a7a-4654-b7d3-b5deb621ee6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Features']/parent::*</value>
      <webElementGuid>53456928-aa16-47d8-a353-de421609409c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>1bc7da7e-ee20-4b2d-b573-edab868c8629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Features' or . = 'Features')]</value>
      <webElementGuid>b790f944-df03-4dc4-baf0-39605a4efb67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
