<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logged_in_username</name>
   <tag></tag>
   <elementGuidId>83e4d793-4f64-480b-ae14-9c33be94e5b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='avatar_user_name']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.chakra-text.css-9ar98d</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'vice' or . = 'vice')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0cab8d39-3b71-4e2b-befb-c9f9979ecbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-9ar98d</value>
      <webElementGuid>581daa22-5539-4fe8-b1e6-4751998f179a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>vice</value>
      <webElementGuid>4aeec1a1-14df-4105-ab14-5b08a8fa7f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avatar_user_name&quot;)/p[@class=&quot;chakra-text css-9ar98d&quot;]</value>
      <webElementGuid>8c1cf357-c96a-46e2-b585-42c089db4954</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='avatar_user_name']/p</value>
      <webElementGuid>1dd0677d-f408-4599-85b6-204a562b458a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Features'])[1]/following::p[1]</value>
      <webElementGuid>d4d339e3-d74d-4289-88fc-e6b10f88c95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::p[2]</value>
      <webElementGuid>f09c5202-cbd8-4bb6-87fe-7a6526864b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of use'])[1]/preceding::p[3]</value>
      <webElementGuid>e4481d82-e0e1-4e39-9ca5-62064c6276d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='vice']/parent::*</value>
      <webElementGuid>219d3fa0-0e18-4ef4-ab41-22458944c5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>bbdc8db3-d254-4b44-aff1-2e34d2d7659e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'vice' or . = 'vice')]</value>
      <webElementGuid>0631340f-6cd1-43e3-baa2-32e736966c06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
