<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_For Me</name>
   <tag></tag>
   <elementGuidId>814a683d-b342-4733-9b65-0d9dc2f1da17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='personalizedFeed']/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.pull-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>48925bd7-da27-4f8c-b1b6-ee7dfe9c6787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-left</value>
      <webElementGuid>b79a2612-9aa3-4422-b8a4-3a9b763dfcf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>For Me</value>
      <webElementGuid>530cd188-3a88-4053-9287-713c750b370b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personalizedFeed&quot;)/div[@class=&quot;panel-title pull-left&quot;]/h2[@class=&quot;pull-left&quot;]</value>
      <webElementGuid>a7e487ee-3876-4a3d-b58a-6e0f83e77502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/web/Page_Followed Topics - Gather/iframe_Cancel_wtForumIframe1666627991071</value>
      <webElementGuid>6f31d0dc-1e40-4f11-b47b-3be9c719ae20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personalizedFeed']/div/h2</value>
      <webElementGuid>593b62b7-a17c-4ea8-b305-94615024df77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::h2[1]</value>
      <webElementGuid>4f01be97-5aef-4ebb-89e8-08d33a71616e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modal title'])[1]/following::h2[1]</value>
      <webElementGuid>4bb75e34-506c-4995-adf7-9c2cced87456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Topic'])[1]/preceding::h2[1]</value>
      <webElementGuid>a3d80232-43be-459c-9100-7796c446e8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='For Me']/parent::*</value>
      <webElementGuid>6ae2dec7-04c4-4d2c-b6a4-ea1f7acc94e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>9d199a2b-ee1c-449e-90ce-c284ee99d8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'For Me' or . = 'For Me')]</value>
      <webElementGuid>bae00370-46fc-4a1e-9457-d48341cd9864</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
