<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Cancel_wtForumIframe1666627991071</name>
   <tag></tag>
   <elementGuidId>01322180-32ee-4e45-894a-a34dd3f8e063</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wtForumIframe1666627991071</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>94bffa2c-07fa-49bc-b3ee-a5371eac4cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wtForumIframe1666627991071</value>
      <webElementGuid>865b60da-32ac-4e97-8448-eb8aa3b45216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wtForumIframe1666627991071</value>
      <webElementGuid>f21f3250-1bf3-40f3-a6de-97ae45161954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://wt-community-test.lorehealthcare.io/search?do=subscribed&amp;action=doSearch&amp;embedded=1</value>
      <webElementGuid>cc530900-612b-430e-9a62-e099fda69156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>89a13bf0-164e-427f-89b9-232f7a573bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>700px</value>
      <webElementGuid>bbae1261-edca-41dc-b746-f399ed8ed8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ac60ae44-33ee-435a-82a1-80810cdd1685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>b2a8c1c3-be01-4715-947d-205a0bda39bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>92bb7bc0-9486-4910-baba-d85e9f632e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wtForumIframe1666627991071&quot;)</value>
      <webElementGuid>596ee1d7-5e59-4419-a65c-468238f76e39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='wtForumIframe1666627991071']</value>
      <webElementGuid>8b863994-0902-4d76-bcec-814f4343a969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframeParent1666627991071']/iframe</value>
      <webElementGuid>00d4394a-36ee-4b97-b29f-19bfb7924575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8c95f8fe-ac10-4b99-aa8c-21df64f091ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'wtForumIframe1666627991071' and @name = 'wtForumIframe1666627991071' and @src = 'https://wt-community-test.lorehealthcare.io/search?do=subscribed&amp;action=doSearch&amp;embedded=1']</value>
      <webElementGuid>f3cb8b57-6cbe-41d0-8a46-45b9fde77ad8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
