<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Change_password</name>
   <tag></tag>
   <elementGuidId>36632303-1950-4b7e-a0ab-f04b5049cced</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type = 'button' and (text() = 'Change' or . = 'Change')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Change' or . = 'Change')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fee03456-269d-41ab-98ce-7a370f2fbb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07c1c9c4-52dc-4842-a6eb-5f48595181ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-id6k57</value>
      <webElementGuid>4a8f22cb-35de-4214-8f87-3c6c91eb7a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change</value>
      <webElementGuid>98ab398a-942b-40b6-9e84-9e6f92870f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-:r8:--tabpanel-0&quot;)/div[@class=&quot;SettingsPage_container__2nJ+L css-0&quot;]/div[@class=&quot;SettingsPage_split__Pd-nM css-155ff3i&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1pefthl&quot;]/button[@class=&quot;chakra-button css-id6k57&quot;]</value>
      <webElementGuid>b5bef449-7311-4d0c-b902-5087d4082078</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//button[@type = 'button' and (text() = 'Change' or . = 'Change')])[2]</value>
      <webElementGuid>99cd3642-6b90-4bb3-8dae-8dd657f4ad63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
