<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birthdate_cellphone</name>
   <tag></tag>
   <elementGuidId>8ed5ae5b-b676-4f27-b3fb-6976fb5e75f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cellphone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cellphone</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'cellphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72971951-508a-4b23-b682-9f24cf597740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cellphone</value>
      <webElementGuid>34bfb7e5-f2b7-4847-99ab-f9e19eef9669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>38af19bc-0626-448e-bd98-598dfe0ed7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input field css-1ohbhgu</value>
      <webElementGuid>4c74554e-5da2-4637-ad56-61b7e853e3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cellphone</value>
      <webElementGuid>dd5ec568-77bc-4fe8-a0d6-60624e88e713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>name(&quot;cellphone&quot;)</value>
      <webElementGuid>2fa3c2b1-f095-4d66-82bb-32598efcc6f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cellphone']</value>
      <webElementGuid>3c54a5ee-7135-4902-9350-f6f9387358c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r8:--tabpanel-0']/div/div[3]/div/form/div[5]/div/input</value>
      <webElementGuid>6e68c5dd-605b-4735-b174-6d6468704333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>67e0b091-a93e-4716-913e-e6d7f38f2eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cellphone' and @type = 'tel']</value>
      <webElementGuid>7c7e06f3-5633-4fda-9c04-4cabfa960787</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
