<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Sex</name>
   <tag></tag>
   <elementGuidId>392d861f-2e2e-4d7a-8f70-f86277e183ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gender']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gender</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a7b63fa5-5d35-44f3-91a5-95a5636d9552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>3c6db88f-c61f-4e5c-9b76-ca8bbb30b0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>e640adc5-dce9-4875-b512-af662ec03ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select field css-1hokd9z</value>
      <webElementGuid>7c87e343-d00a-44a6-8109-f27ccfd082a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an answerMaleFemaleDecline to answer</value>
      <webElementGuid>8f2ac00a-006f-48ef-939f-163489e37ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gender&quot;)</value>
      <webElementGuid>41ef82f8-45b6-4d56-acda-37cdfaf8b497</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gender']</value>
      <webElementGuid>f2bea0e2-44d9-46bb-8b48-0bf098a37aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r8:--tabpanel-0']/div/div[3]/div/form/div[8]/div/select</value>
      <webElementGuid>45bf2e4d-f02a-412c-a52c-f32180c6b9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zipcode'])[1]/following::select[2]</value>
      <webElementGuid>942dfc40-f4ab-4847-8531-293f713c0a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::select[2]</value>
      <webElementGuid>460d5830-6940-4dcd-8537-d0855eeeb6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Changes'])[1]/preceding::select[1]</value>
      <webElementGuid>b6ae6f02-c925-4c85-9780-a4e2b65c406f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of use'])[1]/preceding::select[1]</value>
      <webElementGuid>7257c7fd-5f87-4b07-bce3-ba1930a39421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>be215f75-565b-4871-97b4-bb206cb8e0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'gender' and @id = 'gender' and (text() = 'Select an answerMaleFemaleDecline to answer' or . = 'Select an answerMaleFemaleDecline to answer')]</value>
      <webElementGuid>c3cde12b-24bd-474b-97a5-533c6c51a0a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
