<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pronoun</name>
   <tag></tag>
   <elementGuidId>85560006-fa54-48c0-9a2a-9e829b0f6912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pronoun']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pronoun</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>31f71d28-8d71-4336-a634-5c69da5c4426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pronoun</value>
      <webElementGuid>f128b6ab-7a6d-4fef-bc59-c72df9bb6cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pronoun</value>
      <webElementGuid>86733d24-46e9-44b2-9438-f7a78c11e936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select field css-1hokd9z</value>
      <webElementGuid>163c9933-f55e-40bf-adea-8deb99413f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an answerHe/HimShe/HerThey/Them</value>
      <webElementGuid>16ac6967-cd6a-4181-9c22-9b7cb34a594f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pronoun&quot;)</value>
      <webElementGuid>0f774c5c-2049-4cc8-acf7-1cc8102b21fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pronoun']</value>
      <webElementGuid>d829ad12-6357-425a-9313-e1a2715a3845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r8:--tabpanel-0']/div/div[3]/div/form/div[7]/div/select</value>
      <webElementGuid>aa74c7b5-060a-4142-a611-0ddac3049c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zipcode'])[1]/following::select[1]</value>
      <webElementGuid>7f5278c4-17f0-4424-9643-204af7c09c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::select[1]</value>
      <webElementGuid>5191eda8-4fd1-4597-b81f-b6dad58bd5e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Changes'])[1]/preceding::select[2]</value>
      <webElementGuid>1ad25aee-2fc0-4748-aa5e-e4e04fc7eb49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of use'])[1]/preceding::select[2]</value>
      <webElementGuid>867823ee-0ff6-4e66-bb01-3e942b501501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4d009ae6-58fe-4f83-a5fb-b654fcdfec98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'pronoun' and @id = 'pronoun' and (text() = 'Select an answerHe/HimShe/HerThey/Them' or . = 'Select an answerHe/HimShe/HerThey/Them')]</value>
      <webElementGuid>8f01178e-8244-46f8-a836-e60a2753120a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
